<?php

namespace Alagunto\EzSchedules;

use Alagunto\EzSchedules\Builder\ProxifiedRepetitionsReaderQueryBuilder;
use Alagunto\EzSchedules\Builder\ScheduleReaderQueryBuilder;
use Alagunto\EzSchedules\Builder\ScheduleCreatorQueryBuilder;
use Alagunto\EzSchedules\Proxies\ScheduledRepetition;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;

/**
 * Trait IsAScheduleItem
 * @package Alagunto\EzSchedules
 * @method static static from(\Carbon\Carbon|string $from)
 * @method static static to(\Carbon\Carbon|string $to)
 */
trait IsAScheduleItem
{
    public static function schedule() {
        return new ScheduleCreatorQueryBuilder(static::class);
    }

    public function newEloquentBuilder($query) {
        return new ScheduleReaderQueryBuilder($query);
    }

    public static function raw() {
        return (new static)->newRawQuery();
    }

    public function newRawQuery() {
        $builder = new \Illuminate\Database\Eloquent\Builder($this->newBaseQueryBuilder());

        $builder = $builder->setModel($this)
            ->with($this->with)
            ->withCount($this->withCount);

        return $this->registerGlobalScopes($builder);
    }

    /**
     * @return ScheduledRepetition|null
     */
    public function repetition() {
        if(is_null($this->repetition_id))
            return null;

        return new ScheduledRepetition(RepetitionStrategiesStorage::find(
            $this->repetition_id
        ));
    }

    public static function repetitions() {
        $query = RepetitionStrategiesStorage::query();

        $proxy = new ProxifiedRepetitionsReaderQueryBuilder($query->getQuery());
        $proxy->setModel($query->getModel());

        $proxy->where("item_model", static::class);

        return $proxy;
    }

    public function saveIfNotDuplicate() {
        // We do not prevent savings of non-repeated items
        if(is_null($this->repetition_id))
            return $this->save();

        // But if there is an item generated by that repetition starting at that time...
        if(static::where("starts_at", $this->starts_at)->where("repetition_id", $this->repetition_id)->count() > 0) {
            return null;
        }

        return $this->save();
    }
}